name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: out

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Деплой только для main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy project to dev branch
        run: |
          git fetch origin dev
          git checkout dev

      - name: Remove old files from dev branch
        run: |
          rm -rf ./*
          git rm -r -f . || true

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: out

      - name: Copy build to branch
        run: |
          git config --global user.email "bogdnapis@gmail.com"
          git config --global user.name "apis"
          ls -la out
          cp -r out/* .
          git add .
          git commit -m "Automated deploy to dev"
          git push origin dev --force
      - name: Send email notification on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL}}
          password: ${{ secrets.P }}
          subject: 'Successful Deployment to Dev - ${{ github.repository }}'
          to: bogdanapis@gmail.com
          from: GitHub Actions <bogdanapis@gmail.com>
          body: 'The deployment to the dev environment for ${{ github.repository }} was successful. Commit: ${{ github.sha }}'

      - name: Send email notification on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.P }}
          subject: 'Failed Deployment to Dev - ${{ github.repository }}'
          to: bogdanapis@gmail.com
          from: ${{ secrets.EMAIL }}
          body: 'The deployment to the dev environment for ${{ github.repository }} failed. Commit: ${{ github.sha }}. Please check the GitHub Actions logs for details.'
